window.FG_FAQS = [
['what is pascalogix structura','Pascalogix Structura is the institutional architecture that gives Maynard Rafael Pascasio’s governance practice its permanent form, built across three aligned entities.'],
['who founded pascalogix structura','Pascalogix Structura was founded by Maynard Rafael Pascasio, CPA, licensed in May 1998.'],
['where are you based','Pascalogix Structura is based in Koronadal City, South Cotabato, Philippines, with a global-facing commercial arm.'],
['what is pre-erp governance','Pre-ERP Governance is the discipline of putting records, decision rights, and accountability in place before any enterprise system.'],
['why do you say systems fail before software fails','Because technology mirrors existing disorder. Governance must precede digitization, otherwise automation makes disorder faster and more expensive.'],
['what problem do you solve','Organizations lose feeling when work moves faster than documentation. Pascalogix Structura makes accountability visible again.'],
['what sectors do you cover','Public finance, regulated utilities, private construction, lending, procurement, inventory custody, workforce costing, subcontractor performance, SMEs, and donor-funded activity.'],
['what is your view on ai','AI augments speed. It does not create accountability. The gap must be closed at the governance layer first.'],
['is this a consulting firm','Partly. Commercial implementation is done by Pascalogix Structura Global Systems, while core IP stays in the OPC.'],
['how is the mission funded','Commercial work with North American clients funds the capacity-building work in the Philippines and similar markets.'],
['what is fellowgrid','FellowGrid is the talent development and IP custody layer that connects trained fellows to institutional assignments through governed placement, not informal referral.'],
['is fellowgrid a job board','No. FellowGrid is not a job board.'],
['is fellowgrid a recruitment agency','No. Placement protects both the fellow and the institution.'],
['how is fellowgrid different from a directory','It is a governed roster. Every fellow carries a competency record, placement history, and IP custody trail.'],
['what is an ip custody trail','An IP custody trail is a record linking work produced under Pascalogix Structura back to its origin so it remains traceable and defensible.'],
['why keep a custody trail','So work stays traceable to its origin and defensible under scrutiny.'],
['what is your principle on talent','Talent without a governing record is exposure without a name. FellowGrid is the record.'],
['who can become a fellow','The design targets displaced workers, ALS completers, and communities isolated by geography, politics, economics, or ethnicity.'],
['do i need a degree','No. The model values capability and evidence over credentials alone.'],
['is fellowgrid live now','Full architecture is under development. Institutional briefing is available upon engagement.'],
['what does fellowgrid operate','FellowGrid operates the Miezie C. Alvarez Academy for Youth Transformation and the Pascasio Fellowship for Strategic Resilience.'],
['what is the academy for','The Academy is for youth capacity building.'],
['what is the fellowship for','The Fellowship is for strategic consultancy and resilience work, formerly called School of Strategic Consultancy.'],
['what will fellows learn','Fellows will learn workflow legibility, decision rights, evidence integrity, and accountability lines.'],
['what is workflow legibility','Workflow legibility means identifying how work physically moves through people and sites before systematizing.'],
['what are decision rights','Decision rights define who owns the decision versus who owns the record.'],
['what is evidence integrity','Evidence integrity establishes rules so source records are real and traceable.'],
['what are accountability lines','Accountability lines reconnect roles and reporting so leadership can feel what is happening operationally.'],
['where is it delivered','It is designed for communities isolated by geography, so delivery adapts to context.'],
['who runs these programs','The Pascalogix Fellowship Foundation runs the capacity-building programs.'],
['where is ip held','IP is held in Pascalogix Structura OPC, which houses the IP Vault, Intelligence Labs, and Simulative Labs.'],
['do fellows own ip','No. IP is held centrally. Fellows hold custody records of their contribution.'],
['what is the ip vault','The IP Vault is the repository for governance models and methods.'],
['what are intelligence labs','Intelligence Labs are the research function for governance intelligence.'],
['what are simulative labs','Simulative Labs are the policy development and simulation function.'],
['does the commercial arm own ip','No. Global Systems implements and licenses. It does not hold core IP.'],
['why separate ip from commercial','To protect provenance and deter control assault.'],
['what is the 70 percent equity doctrine','The open corporations hold 70 percent equity for control.'],
['how are institutions protected','Institutions are protected through governed placement, competency records, and traceable trails.'],
['how are fellows protected','Fellows are protected through formal roster placement with defined scope, not informal referral.'],
['how do i engage','Request an institutional briefing.'],
['do you work internationally','Yes, through Global Systems.'],
['do you implement erp','No. Pascalogix Structura works before ERP to prepare governance.'],
['can you help with audits','Yes. Evidence integrity and accountability cartography are core.'],
['do you work with construction','Yes. Construction and civil works are part of the formation background.'],
['what is accountability cartography','Accountability cartography makes money flows, work, and responsibility visible where informal routes have taken over.'],
['how are you different from consultants','Pascalogix Structura starts with pain and records, not software, and leaves a governing order.'],
['can donors fund fellowgrid','Yes. The Foundation is designed for funder support targeting vulnerable groups.'],
['is there a public site','Yes, pascalogixstructura.github.io is the practice overview site.'],
['what is your guiding line','Governance is not built by the people who announce it. It is built by the people who stay after the announcement to write it down.']
];
