window.FG_FAQS=[
['what is pascalogix structura','Pascalogix Structura is the parent governance-first systems architecture behind FellowGrid. It turns human judgment, field evidence, workflows, approvals, records, and accountability into structured operating systems before ERP, dashboards, automation, or AI are allowed to scale.'],
['what are pascalogix structura business and advocacy','Business: governance-grade systems, advisory tools, training products, portfolio engines, readiness assessments, workflow templates, AI-assisted operating shells, and enterprise proof systems. Advocacy: human-gated technology, evidence before automation, dignity before extraction, readiness before AI, and structured opportunity pathways.'],
['what is pascalogix structura fellowgrid','Pascalogix Structura FellowGrid, or FellowGrid, is the platform of Pascalogix Structura for learning, proof-building, portfolio compilation, and opportunity deployment. It houses LMS++, course intake, learner profiles, FB-type feeds, LinkedIn-type proof profiles, finisher portfolios, and the separate hiring be-funnel.'],
['what is fellowgrid','FellowGrid is the platform of Pascalogix Structura for course intake, LMS++ learning execution, live scoring, portfolio proof, and opportunity deployment.'],
['what is lms++','LMS++ is an engine inside FellowGrid. It handles course pack intake, structured lessons, modules, mini-capstones, score sheets, remediation, and portfolio compilation.'],
['what is social proof lms','Social Proof LMS++ combines FB-type interaction with LinkedIn-type professional proof inside FellowGrid.'],
['what is fb type layer','The FB-type layer logs course posts, module posts, comments, submissions, reviewer threads, remediation, and announcements.'],
['what is linkedin type layer','The LinkedIn-type layer shows skills, badges, proof posts, capstones, reviewer notes, finisher status, and deployment readiness.'],
['what is agentic ai','The FellowGrid Agentic AI is a guided action bot that answers FAQs, opens pathways, routes users, prepares intake, suggests next steps, and escalates to a human agent when needed.'],
['can i talk to human agent','Yes. The bot can route you to the Human Agent Chatroom, generate an escalation note, and prepare a call or email request for Maynard or an assigned human agent.'],
['can the bot call me','The static shell cannot place a live phone call by itself. It can generate a call request and pass your contact details to a human agent for follow-up.'],
['can the bot bring maynard to chat','The bot can create a human-agent escalation request for Maynard. A real-time live chat needs backend messaging integration.'],
['what is course intake','Course intake receives a book, manual, PDF, or course pack and prepares it for module creation.'],
['what is student intake','Student intake captures identity, background, skills, device access, goal, urgency, and track fit.'],
['what is a lead','A lead is a student, employer, sponsor, partner, or enterprise contact created from intake or inquiry.'],
['what happens after intake','After intake, the user becomes a lead, then moves to access routing, orientation, and self-paced course.'],
['what is paywall','The paywall manages free preview, paid course, sponsored seat, certification, or enterprise access.'],
['what is orientation','Orientation explains the course rules, proof outputs, remediation path, and portfolio build.'],
['what is self paced','Self-paced means learners progress through modules while producing scored outputs and portfolio proof.'],
['what is a module','A module has lessons, exercises, mini-capstone, score sheet, remediation path, and portfolio link.'],
['what is a structured lesson','A structured lesson has purpose, source, explanation, example, exercise, output requirement, and portfolio link.'],
['what is mini capstone','A mini-capstone is a module-level proof output.'],
['who decides capstones','Maynard inputs or approves capstones; the system structures but the human gate governs proof.'],
['what is live score sheet','It records completion, accuracy, evidence quality, narration, correction compliance, and presentation.'],
['is there failure','No. Weak output goes to remediation.'],
['what is remediation','Remediation is the improvement lane for incomplete, weak, unclear, or unsupported output.'],
['what is portfolio compiler','The Portfolio Compiler is an engine inside FellowGrid that gathers accepted outputs, score sheets, reviewer notes, remediation logs, and final capstones.'],
['what is live portfolio','It updates as accepted proof outputs are added.'],
['what is finisher','A finisher completes modules, remediation if any, final capstones, and portfolio compilation.'],
['what is finisher portfolio','It is the final proof pack for completed learners.'],
['what is finisher database','It stores finishers by course, skill, score, capstone, readiness, and deployment fit.'],
['what is hiring be funnel','The Hiring Be-Funnel is an engine inside FellowGrid, separate from learning, that pulls finishers for employers or clients.'],
['is hiring separate','Yes. Learning creates finishers; hiring pulls qualified finishers.'],
['how supply to employers','Employer demand becomes filters; matching finishers are pulled and proof packs are submitted.'],
['how supply to mercor','Use portfolio-verified finishers matched by skill, score, capstone, readiness, and availability.'],
['what is employer intake','It captures role, tools, English level, workload, rate, availability, and proof requirements.'],
['what is candidate proof pack','It includes profile, course, scores, capstones, reviewer notes, and deployment brief.'],
['what is reverse be funnel','It starts from need or outcome and pulls backward through proof, skills, and records.'],
['what is course registry','It is the master list of all course houses.'],
['what is course house','It is the dedicated home for one course.'],
['what is course pack builder','Course Pack Builder is an engine inside FellowGrid that ingests a course pack, derives modules, creates lessons, asks capstones, and prepares publishing.'],
['can it upload course pack','The shell is prepared; real upload needs backend storage.'],
['can it generate modules','Yes, from the course pack with human-approved capstones.'],
['can it generate lessons','Yes, using the course pack as the governing source.'],
['what are final capstones','The two final capstones are the strongest end-course proof outputs.'],
['why two final capstones','Two final capstones prove both technical capability and applied judgment.'],
['what is admin control room','It monitors intake, course packs, submissions, remediation, payments, portfolios, and hiring queues.'],
['what is proof post','A proof post is a professional artifact from accepted outputs or reviewer endorsements.'],
['what is activity log','An activity log records what happened in the learning workflow.'],
['what is auto logging','Every process action creates a feed log; every accepted output creates professional proof.'],
['what is proprietary status','FellowGrid is proprietary Pascalogix Structura work.'],
['what is no mining','No unauthorized scraping, model training, or extraction of content or records.'],
['what is role readiness','It is deployment fitness based on proof, scores, capstones, and reviewer notes.'],
['what is deployment brief','It summarizes why a finisher fits a role or client need.'],
['what is score threshold','Below threshold goes to remediation; above threshold moves to portfolio.'],
['what is reviewer thread','It is the feedback chain attached to a learner output.'],
['what should i do next','Use the platform shell, then connect backend, upload, database, paywall, login, reviewer tools, and human-agent routing.']
];